apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-app

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: employee-app

  template:

    metadata:
      labels:
        app: employee-app

    spec:

      imagePullSecrets:
        - name: ecr-secret

      containers:

        - name: employee-app

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 80

          env:

            - name: DB_HOST
              value: {{ .Values.db.host | quote }}

            - name: DB_USER
              value: {{ .Values.db.user | quote }}

            - name: DB_NAME
              value: {{ .Values.db.name | quote }}

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
